/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'var(--border)',
        'border-hover': 'var(--border-hover)',
        input: 'var(--border)',
        ring: 'var(--brand-primary)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        surface: 'var(--surface)',
        'surface-hover': 'var(--surface-hover)',
        'surface-raised': 'var(--surface-raised)',
        'surface-elevated': 'var(--surface-elevated)',
        shell: 'var(--bg-shell)',
        overlay: 'rgba(var(--black-rgb), 0.72)',
        primary: {
          DEFAULT: 'var(--foreground)',
          foreground: 'var(--background)',
        },
        secondary: {
          DEFAULT: 'var(--surface-hover)',
          foreground: 'var(--foreground)',
        },
        destructive: {
          DEFAULT: 'var(--status-danger)',
          foreground: 'var(--foreground)',
        },
        muted: {
          DEFAULT: 'var(--surface)',
          foreground: 'var(--muted)',
        },
        accent: {
          DEFAULT: 'var(--surface-hover)',
          foreground: 'var(--foreground)',
        },
        popover: {
          DEFAULT: 'var(--surface)',
          foreground: 'var(--foreground)',
        },
        card: {
          DEFAULT: 'var(--surface)',
          foreground: 'var(--foreground)',
        },
        brand: {
          DEFAULT: 'var(--brand-primary)',
          dark: 'var(--brand-dark)',
          dim: 'var(--accent-primary-dim)',
        },
        panel: {
          DEFAULT: 'var(--bg-panel)',
          hover: 'var(--bg-panel-hover)',
          solid: 'var(--bg-panel-solid)',
        },
        'border-subtle': 'var(--border-subtle)',
        'border-medium': 'var(--border-medium)',
        'border-strong': 'var(--border-strong)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'text-inverse': 'var(--text-inverse)',
        'fin-profit': 'var(--fin-profit)',
        'fin-profit-dim': 'var(--fin-profit-dim)',
        'fin-loss': 'var(--fin-loss)',
        'fin-loss-dim': 'var(--fin-loss-dim)',
        'fin-warning': 'var(--fin-warning)',
        'fin-warning-dim': 'var(--fin-warning-dim)',
        'fin-info': 'var(--accent-primary)',
        'fin-info-dim': 'var(--accent-primary-dim)',
        'data-agent-cio': 'var(--data-agent-cio)',
        'data-agent-fundamental': 'var(--data-agent-fundamental)',
        'data-agent-quant': 'var(--data-agent-quant)',
        'data-agent-macro': 'var(--data-agent-macro)',
        'data-agent-risk': 'var(--data-agent-risk)',
        'data-agent-catalyst': 'var(--data-agent-catalyst)',
      },
      borderRadius: {
        lg: '16px',
        md: '12px',
        sm: '8px',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
