sonar.projectKey=Piti9427_my-port-stock
sonar.projectName=my-port-stock
sonar.sources=backend,frontend/src
sonar.tests=backend/tests,frontend/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/.temp/**,backend/tests/**/*.sql
